name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  packages: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2.1.1
        with:
          app-id: ${{ secrets.GIT_APP_CLIENT_ID }}
          private-key: ${{ secrets.GIT_APP_PRIVATE_KEY }}

      - name: Create Release Pull Request
        uses: changesets/action@v1.5.3
        with:
          commit: 'ci: release'
          publish: pnpm changeset publish
          title: 'ci: release'
          version: pnpm changeset version
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_CONFIG_PROVENANCE: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
